// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	User *User  `json:"user"`
}

type NewComment struct {
	Text   string `json:"text"`
	PostID string `json:"postId"`
	UserID string `json:"userId"`
}

type NewPost struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name       string  `json:"name"`
	AvatarURL  *string `json:"avatarUrl"`
	LineUserID *string `json:"lineUserId"`
}

type Post struct {
	ID       string     `json:"id"`
	Text     string     `json:"text"`
	User     *User      `json:"user"`
	Comments []*Comment `json:"comments"`
}

type User struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	AvatarURL  *string `json:"avatarUrl"`
	LineUserID *string `json:"lineUserId"`
}
