query posts {
  posts {
    id
    text
    user {
      id
      name
      avatarUrl
    }
    comments {
      id
      text
      user {
        id
        name
        avatarUrl
      }
    }
  }
}